### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by chitianqilin** [parilo/tars-rl#3]
Hi

When I run the code with Python 3.7 on Windows 8.1, for the run_agents part, there is always an error that occurs multiple times:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
`
I can identify it happens when the code calls multiprocessing:
`p = Process(target=run_agent, args=(algo_config, agent_config))
`
Does anyone have the same problem?

**Comment by chitianqilin** [comment]
Sorry, the above error is hard to read, I try it again here.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  File "F:\git\tars-rl\misc\config.py", line 37, in __getattr__
    if hasattr(self._config, name):
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
